### ISSUE TITLE
Compatibility with mpv_thumbnail_script?

### ISSUE THREAD

**Issue by D3SOX** [maoiscat/mpv-osc-modern#16]
I tried to use this together with [mpv_thumbnail_script](https://github.com/TheAMM/mpv_thumbnail_script), but then the default MPV OSC is shown again. When moving it out of the scripts directory, it works again
Is this not compatible and if yes is there a workaround?

**Comment by NaiveInvestigator** [comment]
we can instead integrate this script instead. 

https://github.com/po5/thumbfast

It does the same thing but I feel is easier to implement too I think imho

**Comment by D3SOX** [comment]
Thanks for implementing it!
