### ISSUE TITLE
Not Reading ~/.config/mpv/script-opts/osc.conf

### ISSUE THREAD

**Issue by blueray453** [maoiscat/mpv-osc-modern#17]
There are few configs https://github.com/maoiscat/mpv-osc-modern#configuration

None of these take effect.

Even `title = '1234',` does not work.

```
% mpv -v -v
...
[cplayer] Error parsing option profile-cond (option not found)
[cplayer] /home/ismail/.config/mpv/mpv.conf:153: setting option profile-cond='p["idle-active"]' failed.
[cplayer] Error parsing option profile-restore (option not found)
[cplayer] /home/ismail/.config/mpv/mpv.conf:154: setting option profile-restore='copy-equal' failed.
```

**Comment by blueray453** [comment]
One more issue. When playing video it shows pause button. When paused, it show play button.

**Comment by maoiscat** [comment]
1. thanks and the configuration section is updated, it should be correct now.
2. "title" is the text shown above the control pannle when paused, you can check it later.
3. you may paste your config file to help debugging.
4. to swap the play/pause button, goto line 1212 in the lua file , seeing something like "mp.get_property('pause') == 'yes'", and change yes to no.

**Comment by blueray453** [comment]
Here is the `mpv --log-file=output.txt`.

[output.txt](https://github.com/maoiscat/mpv-osc-modern/files/9215832/output.txt)

```
[   0.004][e][cplayer] Error parsing option profile-cond (option not found)
[   0.004][e][cplayer] /home/ismail/.config/mpv/mpv.conf:156: setting option profile-cond='p["idle-active"]' failed.
[   0.004][e][cplayer] Error parsing option profile-restore (option not found)
[   0.004][e][cplayer] /home/ismail/.config/mpv/mpv.conf:157: setting option profile-restore='copy-equal' failed.
```
When playing video, it shows `|>`. When video is paused, it shows `||`. It should be opposite.

**Comment by maoiscat** [comment]
i mean attaching your mpv.conf to help tracking your error msg

please try paragraph 4 if you like an opposite play/pause display

**Comment by blueray453** [comment]
I do not like an opposite play/pause display.

There is a **bug in your script**.

In regular video players, when playing a video it shows

![playing-others](https://user-images.githubusercontent.com/855297/181793296-147aa627-ec7e-40ea-8320-eeef783f5f60.png)

In regular video players, when a video is paused it shows

![paused-others](https://user-images.githubusercontent.com/855297/181793317-067aa203-854c-4b47-a5cb-66212c3aea46.png)

with your script, when playing a video it shows

![play](https://user-images.githubusercontent.com/855297/181792048-6c3324c1-570c-47aa-94cd-ea5e799bc790.png)

with your script, when a video is paused it shows

![paused](https://user-images.githubusercontent.com/855297/181792105-2ea85743-b653-490f-a302-c9b72912f7ee.png)

Here is my total mpv.conf file:

```
no-osd-bar
osd-level=0
keep-open=yes
player-operation-mode=pseudo-gui
input-ipc-server=/tmp/mpv-socket
screenshot-directory=~/Pictures/
no-window-dragging
osc=no
```
I did not understand what `paragraph 4` is? paragraph 4 of readme file or your script?

**Comment by blueray453** [comment]
The play-pause issue is solved with 

> to swap the play/pause button, goto line 1212 in the lua file , seeing something like "mp.get_property('pause') == 'yes'", and change yes to no.

**Comment by maoiscat** [comment]
i dont see the profile-cond section in your mpv.conf. it is strange about your error msg.

anyway it only provides an apperance improvement when idle, it does no matter to the osc

**Comment by blueray453** [comment]
Thank you very much. This solved my problem.
