### ISSUE TITLE
Add option to toggle play/pause button

### ISSUE THREAD

**Issue by Hill-98** [maoiscat/mpv-osc-modern#19]
I don't know why the triangle button is now showing while playing, but it doesn't fit most people's intuition.

I know it's possible to modify the script to toggle, but adding an option to toggle them I think would be nicer.

**Comment by maoiscat** [comment]
you can fork and realize such feature.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Zhong ***@***.***> |
| Date | 08/05/2022 02:12 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-modern] Added option to toggle play/pause button (Issue #19) |

I don't know why the triangle button is now showing while playing, but it doesn't fit most people's intuition.

I know it's possible to modify the script to toggle, but adding an option to toggle them I think would be nicer.

**Comment by Hill-98** [comment]
can i submit a pr?

**Comment by Hill-98** [comment]
can i submit a pr?

**Comment by maoiscat** [comment]
sure



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Zhong ***@***.***> |
| Date | 08/05/2022 12:23 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [maoiscat/mpv-osc-modern] Add option to toggle play/pause button (Issue #19) |

can i submit a pr?

**Comment by Hill-98** [comment]
So can we set the default to show ⏸ when playing?

**Comment by maoiscat** [comment]
code is changed
you have what you want
