### ISSUE TITLE
Add proximity based trigger to controls and window button

### ISSUE THREAD

**Issue by he2a** [maoiscat/mpv-osc-modern#20]
Currently the OSC is triggered on mouse movement. It would be great if main controls and window controls are triggered separately based on cursor proximity to trigger zones like the case in [UOSC](https://github.com/darsain/uosc).

**Comment by maoiscat** [comment]
A simple workaround:

line 994:
    add_area('showhide', 0, 0, osc_param.playresx, osc_param.playresy)

chage to:
    add_area('showhide', 0, osc_param.playresy-200, osc_param.playresx, osc_param.playresy)
    add_area('showhide_wc', osc_param.playresx*0.67, 0, osc_param.playresx, 48)

**Comment by he2a** [comment]
Solution works great with `minmousemove=1`. Thanks a lot 👍
