### ISSUE TITLE
Logo is disproportional due to recent change in libass

### ISSUE THREAD

**Issue by jiangzhenjerry** [maoiscat/mpv-osc-modern#28]
Due to a recent change in `libass`, the mpv logo is out of proportion upon startup. It affected not only this theme but also the default osc. After I reported in #https://github.com/mpv-player/mpv/issues/10710, mpv has fixed the issue in their osc, but this modern theme also needs adjustment. Please refer to the linked issue for more details.

<img width="722" alt="1" src="https://user-images.githubusercontent.com/9311082/194733173-5efe1558-5632-44a8-b347-e60d0ca3795b.png">

**Comment by maoiscat** [comment]
fixed
