### ISSUE TITLE
Beautiful OSC only one little tiny thing

### ISSUE THREAD

**Issue by First-Dan** [maoiscat/mpv-osc-modern#32]
Hello, i found your script by coincidence and i loved it
The only thing that i'm missing from it is the **"skip_back/forward"** to be the usual **"skip to next/previous chapter"** instead of +5/+60s, because i already have time skip on my mouse wheel, can you show me how?
Thank you in advance.

**Comment by FinnRaze** [comment]
Edit these functions in modern.lua like this
`  ne.eventresponder['mbtn_left_down'] =
        --function () mp.command('add chapter -1') end
        function () mp.commandv('add','chapter', -1) end
    ne.eventresponder['shift+mbtn_left_down'] =
        function () mp.commandv('frame-back-step') end
    ne.eventresponder['mbtn_right_down'] =
        --function () mp.command('seek -90') end
        function () mp.commandv('seek', -90, 'relative', 'keyframes') end

    --skipfrwd
    ne = new_element('skipfrwd', 'button')

    ne.softrepeat = true
    ne.content = '\xEF\x8E\x9F'
    ne.eventresponder['mbtn_left_down'] =
        --function () mp.command('add chapter +1') end
        function () mp.commandv('add','chapter', 1) end
    ne.eventresponder['shift+mbtn_left_down'] =
        function () mp.commandv('frame-step') end
    ne.eventresponder['mbtn_right_down'] =
        --function () mp.command('seek +87') end
        function () mp.commandv('seek', 87, 'relative', 'keyframes') end`

**Comment by First-Dan** [comment]
> ctrl+f 'seek' to find relative lines and edit these functions like this
> 
> ```
> 
>    ne.eventresponder['mbtn_left_down'] =
>         --function () mp.command('add chapter -1') end
>         function () mp.commandv('add','chapter', -1) end
>     ne.eventresponder['shift+mbtn_left_down'] =
>         function () mp.commandv('frame-back-step') end
>     ne.eventresponder['mbtn_right_down'] =
>         --function () mp.command('seek -90') end
>         function () mp.commandv('seek', -90, 'relative', 'keyframes') end
> 
>     --skipfrwd
>     ne = new_element('skipfrwd', 'button')
> 
>     ne.softrepeat = true
>     ne.content = '\xEF\x8E\x9F'
>     ne.eventresponder['mbtn_left_down'] =
>         --function () mp.command('add chapter +1') end
>         function () mp.commandv('add','chapter', 1) end
>     ne.eventresponder['shift+mbtn_left_down'] =
>         function () mp.commandv('frame-step') end
>     ne.eventresponder['mbtn_right_down'] =
>         --function () mp.command('seek +87') end
>         function () mp.commandv('seek', 87, 'relative', 'keyframes') end`
> ```

Sorry for the late reply but thank you so much! It worked!
Btw, i'm using your fork now and i want to test thumbfast, but it's looking like this
![Screenshot 2023-01-23 223802](https://user-images.githubusercontent.com/118942481/214155692-c96c9287-b826-498e-b21b-575312368b5e.png)
How can i fix this?

**Comment by FinnRaze** [comment]
I didn't modify lines about thumbfast and cannot reproduce this(tested on win8.1&win10).
![mpv-shot0001](https://user-images.githubusercontent.com/84557113/214188566-2801e5e8-5588-4124-b8d6-0fbf6ea03235.jpg)

**Comment by First-Dan** [comment]
Okay, i'll issue it to its developper.
Thank you for your help!
