### ISSUE TITLE
Weird font behaviour on macOS Monterey

### ISSUE THREAD

**Issue by Tsubajashi** [maoiscat/mpv-osc-modern#4]
Hi! interesting script, really appreciate your work.

Now to the matter from the title - it seems to me like the font isnt rendering correctly, and just shows weird values.
![CleanShot 2021-08-27 at 20 32 16](https://user-images.githubusercontent.com/21346945/131173605-2b94ffd6-490b-467c-9132-8c5a5e59c826.png)
Do you know about that behaviour on macOS? or even, would you know a fix?

Thanks in advance!

**Comment by xiaoleichen** [comment]
> fixed it myself. sorry for the confusion.

Could you share how you fixed it? I'm having the same issue. (I've already put .ttf file in ~~/fonts/ folder)

**Comment by nsklaus** [comment]
i have same issue.
i'd be interested to know how this was solved too

**Comment by Tsubajashi** [comment]
I just made sure the font file Was not broken and got it from another repo

**Comment by nsklaus** [comment]
@Tsubajashi 
i tried to get the font from there: https://zavoloklom.github.io/material-design-iconic-font/
and i copied just the ttf file in: `~/.config/mpv/fonts/`
and it's still broken just like your screenshot when you opened the issue..

**Comment by xiaoleichen** [comment]
@nsklaus 
Mac seems to have issue interpreting hexadecimal representations of the icons. Converting to decimal fixes the issue. For example, for previous button, use `ne.content = '\239\142\181'` instead of `ne.content = '\xEF\x8E\xB5'`. 

My fork: https://github.com/xiaoleichen/mpv-settings-mac/blob/main/scripts/osc_modern.lua

**Comment by nsklaus** [comment]
@xiaoleichen 
i tested your fork and confirm that solved the problem. many thanks for the fix!
