### ISSUE TITLE
Which License are you using?

### ISSUE THREAD

**Issue by zjuyk** [maoiscat/mpv-osc-modern#43]
Hi,

I'd like to make a package in ArchLinux for this script. Which License are you using?

Best Regards

**Comment by maoiscat** [comment]
it should be the same as mpv itself. GPL I suppose.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月19日 16:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maoiscat/mpv-osc-modern] Which License are you using? (Issue #43) |

Hi,

I'd like to make a package in ArchLinux for this script. Which License are you using?

Best Regards

**Comment by zjuyk** [comment]
Got it, thanks
