### ISSUE TITLE
In specific cases cause memory leak

### ISSUE THREAD

**Issue by FinnRaze** [maoiscat/mpv-osc-modern#44]
reproduce
1. set `script-opts-add=osc-visibility=always` in mpv.conf and play music.
2. set window minimized
3. when playback changed from a music without cover art to one with cover art,click the window
4. cover art would not show up and memory leak happens.Have to kill the program and unable to get a resultful log
![屏幕截图 2023-04-19 143743](https://user-images.githubusercontent.com/84557113/233973518-006fc329-f82f-4e1f-94e7-c271871e9406.jpg)

**Comment by maoiscat** [comment]
will this happen with the built-in osc?



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/24/2023 18:53 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-modern] In specific cases cause memory leak (Issue #44) |

reproduce

set script-opts-add=osc-visibility=always in mpv.conf and play music.
set window minimized
when playback changed from a music without cover art to one with cover art,click the window
cover art would not show up and memory leak happens.Have to kill the program and unable to get a resultful log

**Comment by maoiscat** [comment]
seems something wrong with mpv itself

not sure though



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/24/2023 18:53 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-modern] In specific cases cause memory leak (Issue #44) |

reproduce

set script-opts-add=osc-visibility=always in mpv.conf and play music.
set window minimized
when playback changed from a music without cover art to one with cover art,click the window
cover art would not show up and memory leak happens.Have to kill the program and unable to get a resultful log

**Comment by FinnRaze** [comment]
some more clues: it may be concerned with window size. And if I disable the geometry options in mpv.conf, the problem doesn't show up.

part of log before the problem

[   9.162][v][vo/gpu/win32] reset window bounds: -31520:-31730:0:0
[   9.164][v][vo/gpu] Resize: 0x0
[   9.164][v][vo/gpu] Window size: 1x1 (Borders: l=0 t=0 r=0 b=0)
[   9.164][v][vo/gpu] Video source: 640x640 (72:72)
[   9.164][v][vo/gpu] Video display: (0, 0) 640x640 -> (0, 0) 1x1
[   9.164][v][vo/gpu] Video scale: 0.001563/0.001563
```

normal state
```
[  11.771][v][vo/gpu/win32] reset window bounds: -31840:-32080:640:640
[  11.771][v][vo/gpu/win32] adjusted window bounds: -31840:31:640:640
[  11.773][v][vo/gpu] Resize: 640x640
[  11.773][v][vo/gpu] Window size: 640x640 (Borders: l=0 t=0 r=0 b=0)
[  11.773][v][vo/gpu] Video source: 640x640 (72:72)
[  11.773][v][vo/gpu] Video display: (0, 0) 640x640 -> (0, 0) 640x640
[  11.773][v][vo/gpu] Video scale: 1.000000/1.000000
```

**Comment by zydezu** [comment]
![image](https://github.com/maoiscat/mpv-osc-modern/assets/50119098/d619b414-1374-4d92-a7f2-8c0fd88a3d58)

Memory seems to increase whenever the OSC is showing (and the video is playing).

**Comment by zydezu** [comment]
https://github.com/maoiscat/mpv-osc-modern/assets/50119098/6f539214-8171-4b59-8d32-cffe833f5194

The RAM usage seems to increase when the OSC is visible and the video is being played.

**Comment by zydezu** [comment]
could be related to this though https://github.com/mpv-player/mpv/issues/9014
