### ISSUE TITLE
Add a LISENCE into this repo?

### ISSUE THREAD

**Issue by zjuyk** [maoiscat/mpv-osc-modern#47]
Hi, may I ask which LICENSE are you using in this repo? We are trying to follow [RFC16](https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0016-spdx-license-identifiers.rst). If upstream can't provide a valid LISENCE, I can't keep this package in ArchLinuxCN repo anymore.

**Comment by maoiscat** [comment]
LGPL should be ok

**Comment by zjuyk** [comment]
Accoring to SPDX, there are multi choices. You can choose one.
![image](https://github.com/maoiscat/mpv-osc-modern/assets/76436317/096a54fc-0906-462f-8b89-eed9219d221a)

**Comment by maoiscat** [comment]
lgpl 2.1 or later

**Comment by zjuyk** [comment]
https://github.com/archlinuxcn/repo/commit/33f8662b81988e0cccc0bc77998172cb72a633b9 Done.
