### ISSUE TITLE
Showing the full title on the OSC ...

### ISSUE THREAD

**Issue by SharadJ19** [maoiscat/mpv-osc-modern#49]
![Screenshot_1](https://github.com/maoiscat/mpv-osc-modern/assets/85397332/886b0505-e4cd-4a37-93cb-02634bebbec3)
showing the full title :

[Hi10][Dual-Audio]

how to make it show the full title ,lots of space is left but script somehow isn't using it for display.

**Comment by maoiscat** [comment]
line 1130: lo.button.maxchars = geo.w / 23

change it to something that fit your font width



At 2024-03-08 17:27:14, "Sharad Chandel" ***@***.***> wrote:

Screenshot_1.jpg (view on web)
showing the full title :

[Hi10][Dual-Audio]

how to make it show the full title ,lots of space is left but script somehow isn't using it for display.
