### ISSUE TITLE
script has error in mpv 0.38 and above; shared script property not supported anymore

### ISSUE THREAD

**Issue by emk2203** [maoiscat/mpv-osc-modern#51]
mpv 0.37 only gave a warning, but mpv 0.38 removed the shared_script_properties property. From the release notes:

> --- mpv 0.38.0 ---
> ...
>     - remove shared-script-properties (user-data is a replacement)
> ...
> 

Because of this change, the modernx script now has a lua error `Lua error: /etc/mpv/scripts/modernx.lua:2520: attempt to call field 'shared_script_property_set' (a nil value)`. The OSC doesn't appear anymore, and the script is therefore non-functional.

 What's the best way to fix? A simple replacement of `shared-script-properties` with `user-data` in the script didn't work for me.

**Comment by maoiscat** [comment]
recent mpv updates have deprecated "shared-script-properties" var. it has to move to somewhat "user-property"

however this project is frozen, and i will not make any further change in codes.

**Comment by emk2203** [comment]
Thanks for the update, and also thanks for your initial project, which has brought tremendous comfort to my setup over the years.

If someone else runs into the issue which is WONTFIX in your project, I recommend [zydezu's ModernX fork](https://github.com/zydezu/ModernX) which hopefully continues to be live for a long time.

**Comment by jiangzhenjerry** [comment]
@emk2203 I tried zydezu's fork but found a couple bugs that make it quite inconvenient, so I'm sticking with the original mpv-osc-modern for now. I'm using the nightly mpv build which is way ahead of the stable 0.38 release, but somehow mpv-osc-modern still works perfectly fine.
